name: flames
description: An application for love Test calculator and flames test

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  share: ^2.0.4
  percent_indicator: ^3.4.0
  google_mobile_ads: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: "assets/flamelogo.png"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.


flutter:
  assets:
    - "assets/images/file_main.png"
    - "assets/images/heart_main.png"
    - "assets/images/bike.png"
    - "assets/images/heart2.png"
    - "assets/images/heart3.png"
    - "assets/images/Circle.png"
    - "assets/images/Vector1.png"
    - "assets/images/Vector2.png"
    - "assets/images/&.png"
    - "assets/images/fire.png"
    - "assets/images/heart.png"
    - "assets/images/heartfire.png"
    - "assets/images/Top.png"
    - "assets/images/Vector.png"
    - "assets/images/Vector3.png"
    - "assets/images/Vector4.png"
    - "assets/images/Group.png"
    - "assets/images/heart9.png"
    - "assets/images/Frame3.png"
    - "assets/images/Frame4.png"
    - "assets/images/pc1.png"
    - "assets/images/pc2.png"
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  fonts:
    - family: "Raleway1"
      fonts:
        - asset: "font/Raleway-ExtraBoldItalic.ttf"
          style: "normal"
          weight: 400
    - family: "Raleway2"
      fonts:
        - asset: "font/Raleway-VariableFont_wght.ttf"
          style: "normal"
          weight: 400
    - family: "Raleway-Bold"
      fonts:
        - asset: "font/Raleway-Bold.ttf"
          style: "normal"
          weight: 400
    - family: "Raleway-Medium"
      fonts:
        - asset: "font/Raleway-Medium.ttf"
          style: "normal"
          weight: 400
    - family: "Milonga"
      fonts:
        - asset: "font/Milonga-Regular.ttf"
          style: "normal"
          weight: 400
    - family: "Montserrat"
      fonts:
        - asset: "font/Montserrat-ExtraBold.ttf"
          style: "normal"
          weight: 400
    - family: "Ribeye-Regular"
      fonts:
        - asset: "font/Ribeye-Regular.ttf"
          style: "normal"
          weight: 600
    - family: "Montserrat-Welcomepage"
      fonts:
        - asset: "font/Montserrat-SemiBold.ttf"
          style: "normal"
          weight: 600
    - family: "Montserrat2"
      fonts:
        - asset: "font/Montserrat-Regular.ttf"
          style: "normal"
          weight: 400
    - family: "Montserrat3"
      fonts:
        - asset: "font/Montserrat-Bold.ttf"
          style: "normal"
          weight: 400
    - family: "MPLUSRounded1c"
      fonts:
        - asset: "font/MPLUSRounded1c-ExtraBold.ttf"
          style: "normal"
          weight: 800
    - family: "Montserrat-Medium"
      fonts:
        - asset: "font/Montserrat-Medium.ttf"
          style: "normal"
          weight: 400
    - family: "Comfortaa"
      fonts:
        - asset: "font/Comfortaa-Light.ttf"
          style: "normal"
          weight: 400
    - family: "Comfortaa2"
      fonts:
        - asset: "font/Comfortaa-Bold.ttf"
          style: "normal"
          weight: 400
    - family: "BlackOpsOne"
      fonts:
        - asset: "font/BlackOpsOne-Regular.ttf"
          style: "normal"
          weight: 400
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
